hostinfo:
	gcc -o hostinfo hostinfo.c

mydate: mydate.o
	gcc -o mydate mydate.c

print: printdir.o
	gcc -o printdir printdir.c

cat: mycat.o
	gcc -o mycat mycat.c

pipe: pipe_ls.o
	gcc -o pipe_ls pipe_ls.c
